site_name: KuretaNone
copyright: "&copy; 2025 KuretaNone"
strict: false
use_directory_urls: false
site_url: https://kuretanone.net
theme:
  name: material
  favicon: https://pbs.twimg.com/profile_images/1861427904577708032/-ol_T5TU_400x400.jpg
  icon:
    logo: material/ghost
    repo: material/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark-blue  # ライトテーマ時の色
      toggle:
        icon: material/weather-night
        name: ダークモードに切り替え
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark blue       # ダークテーマ時の色
      toggle:
        icon: material/weather-sunny
        name: ライトモードに切り替え

extra:
  homepage: https://KuretaNone.net
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KuretaNone
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KuretaNone
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@KuretaNone
  generator: false

plugins:
  - obsidian-bridge
  - awesome-nav
  - glightbox
  - search:
      lang: ja
  - backlinks_section:
      title: "Links to this page"
      description: ""
      add_to_toc: false
      hide_if_empty: true
  - git-revision-date-localized:
      strict: false
      enable_creation_date: true
      locale: ja
      timezone: Asia/Tokyo
  - social:
      cards_layout_options:
        font_family: Noto Sans JP

markdown_extensions:
  - footnotes
  - md_in_html
  - obsidian_callouts
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
